version: '3.8'

services:
  app:
    build: .
    ports:
      - "5010:5010"   # Frontend
      - "3001:3001"   # Backend API
    environment:
      - NODE_ENV=production
      - MONGODB_URI=${MONGODB_URI:-mongodb://localhost:27017/testdb}
      - MONGODB_DATABASE_NAME=testdb
      - MONGODB_COLLECTION_NAME=test_results
      - FRONTEND_URL=http://localhost:5010
    restart: unless-stopped
    