// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rbirykrykcdmcpljaqcy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJiaXJ5a3J5a2NkbWNwbGphcWN5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQwMDk2NzIsImV4cCI6MjA2OTU4NTY3Mn0.Z_xowf5NK76rNonOiI9UqdGwerLS9vWdrbC3Cy1KWtc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});